btc/Web/WebBiotec/Models/Config_ConceptosRetail.cs
namespace WebBiotec.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Config_ConceptosRetail
    {
        public int ID { get; set; }

        [Required]
        [StringLength(100)]
        public string RUT { get; set; }

        [Required]
        [StringLength(100)]
        public string FICHA { get; set; }

        [Required]
        [StringLength(100)]
        public string COD_CONCEPTO { get; set; }

        [Required]
        [StringLength(100)]
        public string CONCEPTO { get; set; }

        [Required]
        [StringLength(100)]
        public string COD_CUENTA { get; set; }

        public double PORCENTAJE { get; set; }

        [Required]
        [StringLength(10)]
        public string TIPO_CALCULO { get; set; }
    }
}

btc/Web/WebBiotec/Controllers/Config_ConceptosRetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBiotec.Models;

namespace WebBiotec.Controllers
{
    public class Config_ConceptosRetailController : Controller
    {
        private ModelMantenedores db = new ModelMantenedores();

        [Authorize]
        // GET: Config_ConceptosRetail
        public ActionResult Index(string comboboxCanales="",string comboboxClientes="")
        {

         
            ViewBag.comboboxClientes = comboboxClientes;
            if (comboboxClientes != "0" && comboboxClientes != "")
            {
                string vrut = comboboxClientes.Substring(0, comboboxClientes.IndexOf(";"));
                string vficha = comboboxClientes.Substring(comboboxClientes.IndexOf(";") + 1);
                int cantidad;

                using (var ctx = new Model1())
                {
                    cantidad = ctx.Database.SqlQuery<int>("select count(*) from [dbo].[CONFIG_CADENAS] where RUT =@vRut"
                                     , new SqlParameter("@vRut", vrut))
                                     .SingleOrDefault();
                }

                if (cantidad == 0)
                {
                    if (vficha != "0")
                    {
                        return View(db.Config_ConceptosRetail
                                      .Where(x => x.RUT == vrut && x.FICHA == vficha)
                                      .ToList());
                    }
                    else
                    {
                        return View(db.Config_ConceptosRetail.Where(x => x.RUT == vrut).ToList());
                    }
                }
                else
                {
                    List<string> listaRut;
                    using (var ctx = new Model1())
                    {
                      listaRut = ctx.Database.SqlQuery<string>(
                     "SELECT RUT FROM [dbo].[CONFIG_CADENAS] WHERE CADENA IN(SELECT CADENA FROM [dbo].[CONFIG_CADENAS] WHERE RUT = @vRut)"
                      ,new SqlParameter("@vRut", vrut)).ToList();
                    }
                    // XXXX

                    return View(db.Config_ConceptosRetail.Where(x => listaRut.Contains(x.RUT)).ToList());
                    //return View(db.Config_ConceptosRetail.Where(x => x.RUT == vrut).ToList());
                    //dataSource.StateList.Where(s => countryCodes.Contains(s.CountryCode))

                }




            }
            else
            {
                var result = from e in db.Config_ConceptosRetail
                             orderby e.RUT, e.COD_CONCEPTO
                             select e;

                return View(result);
                //    .OrderBy(x=> x.RUT)
                //    .OrderBy(x=> x.COD_CONCEPTO)
                //    .ToList());
            }

            
        }

        //[HttpPost]
        //public ActionResult Index(string rut)
        //{
        //    return View(db.Config_ConceptosRetail.Where(x => x.RUT == rut).ToList());
            
        //}

        // GET: Config_ConceptosRetail/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Config_ConceptosRetail config_ConceptosRetail = db.Config_ConceptosRetail.Find(id);
            if (config_ConceptosRetail == null)
            {
                return HttpNotFound();
            }
            return View(config_ConceptosRetail);
        }

        // GET: Config_ConceptosRetail/Create
        public ActionResult Create(string comboboxCanales = "", string comboboxClientes = "")

        {
            var listClientesCuentas = Models.DAO.DaoControlDocumento.getMasterCuentas();
            List<SelectListItem> listCuentasContables = new List<SelectListItem>();
            foreach (var item in listClientesCuentas)
            {
                SelectListItem selectedListItem = new SelectListItem
                {
                    Text = item.TEXTO,
                    Value = item.VALOR
                };
                listCuentasContables.Add(selectedListItem);
            }
            //ViewBag.COD_CONCEPTO = listCuentasContables;
            ViewBag.CuentasContables = listCuentasContables;
            return View();
        }

        // POST: Config_ConceptosRetail/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,RUT,FICHA,COD_CONCEPTO,CONCEPTO,COD_CUENTA,PORCENTAJE,TIPO_CALCULO")] Config_ConceptosRetail config_ConceptosRetail, string comboboxCanales = "", string comboboxClientes = "")
        {
            if (ModelState.IsValid)
            {
                db.Config_ConceptosRetail.Add(config_ConceptosRetail);
                db.SaveChanges();
                return RedirectToAction("Index", new { comboboxCanales = comboboxCanales, comboboxClientes = comboboxClientes });
            }
            var listClientesCuentas = Models.DAO.DaoControlDocumento.getMasterCuentas();
            List<SelectListItem> listCuentasContables = new List<SelectListItem>();
            foreach (var item in listClientesCuentas)
            {
                SelectListItem selectedListItem = new SelectListItem
                {
                    Text = item.TEXTO,
                    Value = item.VALOR
                };
                listCuentasContables.Add(selectedListItem);
            }
            ViewBag.CuentasContables = listCuentasContables;
            return View(config_ConceptosRetail);
        }

        // GET: Config_ConceptosRetail/Edit/5
        public ActionResult Edit(int? id, string comboboxCanales = "", string comboboxClientes = "")
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //var listClientesCuentas = Models.DAO.DaoControlDocumento.getClientesCuentas(comboboxClientes);
            var listClientesCuentas = Models.DAO.DaoControlDocumento.getMasterCuentas();
            

            List<SelectListItem> listCuentasContables = new List<SelectListItem>();
            foreach (var item in listClientesCuentas)
            {
                SelectListItem selectedListItem = new SelectListItem
                {
                    Text = item.TEXTO,
                    Value = item.VALOR
                };
                listCuentasContables.Add(selectedListItem);
            }
            ViewBag.CuentasContables = listCuentasContables;
            Config_ConceptosRetail config_ConceptosRetail = db.Config_ConceptosRetail.Find(id);
       

            if (config_ConceptosRetail == null)
            {
                return HttpNotFound();
            }
            return View(config_ConceptosRetail);
        }

        // POST: Config_ConceptosRetail/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,RUT,FICHA,COD_CONCEPTO,CONCEPTO,COD_CUENTA,PORCENTAJE,TIPO_CALCULO")] Config_ConceptosRetail config_ConceptosRetail, string comboboxCanales = "", string comboboxClientes = "")
        {
            if (ModelState.IsValid)
            {
                db.Entry(config_ConceptosRetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { comboboxCanales = comboboxCanales, comboboxClientes = comboboxClientes});
            }
            var listClientesCuentas = Models.DAO.DaoControlDocumento.getMasterCuentas();
            List<SelectListItem> listCuentasContables = new List<SelectListItem>();
            foreach (var item in listClientesCuentas)
            {
                SelectListItem selectedListItem = new SelectListItem
                {
                    Text = item.TEXTO,
                    Value = item.VALOR
                };
                listCuentasContables.Add(selectedListItem);
            }
            ViewBag.CuentasContables = listCuentasContables;
            return View(config_ConceptosRetail);
        }

        // GET: Config_ConceptosRetail/Delete/5
        public ActionResult Delete(int? id, string comboboxCanales = "", string comboboxClientes = "")
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Config_ConceptosRetail config_ConceptosRetail = db.Config_ConceptosRetail.Find(id);
            if (config_ConceptosRetail == null)
            {
                return HttpNotFound();
            }
            return View(config_ConceptosRetail);
        }

        // POST: Config_ConceptosRetail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Config_ConceptosRetail config_ConceptosRetail = db.Config_ConceptosRetail.Find(id);
            db.Config_ConceptosRetail.Remove(config_ConceptosRetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
    }

}

btc/Web/WebBiotec/Views/Config_ConceptosRetail/Create.cshtml
@model WebBiotec.Models.Config_ConceptosRetail

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Crear Cuenta Contable</h2>

@*@using (Html.BeginForm())*@
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "formcreate" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>Config_ConceptosRetail</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RUT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.RUT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RUT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FICHA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.FICHA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FICHA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.COD_CONCEPTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("COD_CONCEPTO", (IEnumerable<SelectListItem>)ViewBag.CuentasContables, new { @class = "k-input form-control" })
                @Html.ValidationMessageFor(model => model.COD_CONCEPTO, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.COD_CONCEPTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.COD_CONCEPTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.COD_CONCEPTO, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group" id="HIDE_CONCEPTO" name="HIDE_CONCEPTO">
            @Html.LabelFor(model => model.CONCEPTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.CONCEPTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CONCEPTO, "", new { @class = "text-danger" })
            </div>
        </div>

         <div class="form-group" id="HIDE_CONCEPTO" name="HIDE_CONCEPTO">
            @Html.LabelFor(model => model.COD_CUENTA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.COD_CUENTA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.COD_CUENTA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PORCENTAJE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PORCENTAJE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PORCENTAJE, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TIPO_CALCULO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("TIPO_CALCULO", new List<SelectListItem>{
                new SelectListItem {Text="%",Value = "%" },
                new SelectListItem {Text="UF",Value = "UF" }
                }, new { @class = "k-input form-control" })
                @*@Html.ValidationMessageFor(model => model.COD_CONCEPTO, "", new { @class = "text-danger" })*@
                @Html.ValidationMessageFor(model => model.TIPO_CALCULO, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.TIPO_CALCULO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.TIPO_CALCULO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TIPO_CALCULO, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index", "Config_ConceptosRetail", new { comboboxCanales = @Request.Params["comboboxCanales"], comboboxClientes = @Request.Params["comboboxClientes"] })" class="btn btn-default">Volver</a>
                <input type="submit" value="Crear" class="btn btn-default" id="CREAR" />
            </div>
        </div>

        @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index", "AspNetUsers")" class="btn btn-default">Volver</a>
                <input type="submit" class="btn btn-default" value="Crear" />
            </div>
        </div>*@
    </div>
}

@*<div>
    @Html.ActionLink("Volver", "Index", new { comboboxCanales = @Request.Params["comboboxCanales"], comboboxClientes = @Request.Params["comboboxClientes"] })
</div>*@


<script>


    //$("#formcreate").on('submit', function (evt) {
    //    var valor = $("#COD_CONCEPTO option:selected").text()
    //    alert(valor);
    //    alert('SELECCIONAR1');
    //    if (VALOR == 'SELECCIONAR') {
    //        alert('SELECCIONAR2');
    //        evt.preventDefault();
    //    }

    //});



    $("#COD_CONCEPTO").change(function () {

        var valor = $("#COD_CONCEPTO option:selected").text()
        valor = valor.substring(valor.indexOf(" ") + 1);
        $("#CONCEPTO").val(valor);

    });
    $(document).ready(function () {

        $('#HIDE_CONCEPTO').hide();

    });

    $(document).ready(function () {

        var valor = $("#COD_CONCEPTO option:selected").text()
        valor = valor.substring(valor.indexOf(" ") + 1);
        $("#CONCEPTO").val(valor);
    });


</script>

btc/Web/WebBiotec/Views/Config_ConceptosRetail/Delete.cshtml
@model WebBiotec.Models.Config_ConceptosRetail

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h3>Estas seguro de eliminar este registro?</h3>
<div>
    @*<h4>Config_ConceptosRetail</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RUT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RUT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FICHA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FICHA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.COD_CONCEPTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COD_CONCEPTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CONCEPTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONCEPTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.COD_CUENTA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COD_CUENTA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PORCENTAJE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PORCENTAJE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIPO_CALCULO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIPO_CALCULO)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Elimnar" class="btn btn-default" />
            @Html.ActionLink("Volver", "Index", new { comboboxCanales = @Request.Params["comboboxCanales"], comboboxClientes = @Request.Params["comboboxClientes"] })
        </div>
    }
</div>

btc/Web/WebBiotec/Views/Config_ConceptosRetail/Details.cshtml
@model WebBiotec.Models.Config_ConceptosRetail

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Config_ConceptosRetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RUT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RUT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FICHA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FICHA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.COD_CONCEPTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COD_CONCEPTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CONCEPTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONCEPTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.COD_CUENTA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COD_CUENTA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PORCENTAJE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PORCENTAJE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIPO_CALCULO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIPO_CALCULO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

btc/Web/WebBiotec/Views/Config_ConceptosRetail/Edit.cshtml
@model WebBiotec.Models.Config_ConceptosRetail

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
    var cuentasClientes = WebBiotec.Models.DAO.DaoControlDocumento.getClientesCuentas(@Request.Params["comboboxClientes"]);
}

<h2>Editar Cuenta Contable</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>Config_ConceptosRetail</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.RUT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.RUT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RUT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FICHA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.FICHA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FICHA, "", new { @class = "text-danger" })
            </div>
        </div>


        @*<div class="form-group">
            <label class="control-label col-md-2">COD_CONCEPTO:</label>
            <div class="col-md-10">
                <select class="form-control" name="comboboxCuentas" id="comboboxCuentas" style="width: 100%;margin:auto">
                    <option value="">SELECCIONAR</option>
                    @foreach (var items in cuentasClientes)
                    {
                        <option value="@items.VALOR">@items.TEXTO</option>
                    }
                </select>
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.COD_CONCEPTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("COD_CONCEPTO", (IEnumerable<SelectListItem>)ViewBag.CuentasContables, new { @class = "k-input form-control" })
                @Html.ValidationMessageFor(model => model.COD_CONCEPTO, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.COD_CONCEPTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.COD_CONCEPTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.COD_CONCEPTO, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group" id="HIDE_CONCEPTO" name="HIDE_CONCEPTO">
            @Html.LabelFor(model => model.CONCEPTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.CONCEPTO, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CONCEPTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.COD_CUENTA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.COD_CUENTA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.COD_CUENTA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PORCENTAJE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PORCENTAJE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PORCENTAJE, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TIPO_CALCULO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TIPO_CALCULO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TIPO_CALCULO, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.TIPO_CALCULO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                 @Html.DropDownList("TIPO_CALCULO", new List<SelectListItem>{
                new SelectListItem {Text="%",Value = "%" },
                new SelectListItem {Text="UF",Value = "UF" }
                }, new { @class = "k-input form-control" })
                @*@Html.ValidationMessageFor(model => model.COD_CONCEPTO, "", new { @class = "text-danger" })*@
                @Html.ValidationMessageFor(model => model.TIPO_CALCULO, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="@Url.Action("Index", "Config_ConceptosRetail", new { comboboxCanales = @Request.Params["comboboxCanales"], comboboxClientes = @Request.Params["comboboxClientes"] })" class="btn btn-default">Volver</a>
                @*@Html.ActionLink("Volver", "Index", new { comboboxCanales = @Request.Params["comboboxCanales"], comboboxClientes = @Request.Params["comboboxClientes"] })*@
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Volver", "Index", new { comboboxCanales = @Request.Params["comboboxCanales"], comboboxClientes = @Request.Params["comboboxClientes"] })
</div>*@


<script>
    $("#COD_CONCEPTO").change(function () {

        var valor = $("#COD_CONCEPTO option:selected").text()
        valor = valor.substring(valor.indexOf(" ") + 1);
        $("#CONCEPTO").val(valor);
  
    });
    $(document).ready(function () {

        $('#HIDE_CONCEPTO').hide();

    });


</script>