btc/Web/WebBiotec/Controllers/PortalWebController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebBiotec.Controllers
{
    public class PortalWebController : Controller
    {
        // GET: PortalWeb
        public ActionResult Index()
        {
            return View();
        }



        public JsonResult cargarClientes()
        {
            var resultado = WebBiotec.Models.DAO.DaoControlPresupuesto.getClientes();
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

    }
}

btc/Web/WebBiotec/Controllers/TradeMarketingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBiotec.Models.DTO;

namespace WebBiotec.Controllers
{
    public class TradeMarketingController : Controller
    {
        // GET: TradeMarketing
        [Authorize]
        public ActionResult ControlPresupuesto()
        {
            return View();
        }

        [Authorize]
        public ActionResult ControlDocumentos()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult ControlDocumentos(string comboboxClientes, string comboboxNumeroDocumento, string engineeFacturaEstado, string txtComentario, string txtFechaEmision, string txtFechaGasto, string txtCuentaContable, string comboboxCuentaContableNueva, string txtNuevaFechaGasto)
        {

            WebBiotec.Models.DAO.DaoControlDocumento.IngresarEstadoFactura(comboboxClientes, comboboxNumeroDocumento, engineeFacturaEstado, txtComentario, txtFechaEmision, txtFechaGasto, txtCuentaContable, comboboxCuentaContableNueva, txtNuevaFechaGasto);
            return View();
        }

        public ActionResult Procedimiento(string comboboxClientes)
        {
            return View();
        }


        public JsonResult cargarClientesJSON()
        {
            var resultado = WebBiotec.Models.DAO.DaoControlPresupuesto.getClientes();
            ComboboxClientes itemTodos = new ComboboxClientes();
            itemTodos.texto = "Seleccionar";
            itemTodos.valor = "0";
            resultado.Add(itemTodos);
            ViewBag.cadenasClientes = resultado;

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        public JsonResult cargarCadenasClientesJSON(string codCanal,string perfil)
        {
            var resultado = WebBiotec.Models.DAO.DaoControlPresupuesto.GetCadenasClientes(codCanal, perfil);
            return Json(resultado, JsonRequestBehavior.AllowGet);

        }

        public static List<ComboboxClientes> cargarClientes()
        {
            var resultado = WebBiotec.Models.DAO.DaoControlPresupuesto.getClientes();
            ComboboxClientes itemTodos = new ComboboxClientes();
            itemTodos.texto = "Seleccionar";
            itemTodos.valor = "0";
            resultado.Add(itemTodos);

            return resultado;

        }

        public JsonResult LoadGraficoVentas(string CODCANAL,string RUTCLIENTE, string MES)
        {
            var resultado = WebBiotec.Models.DAO.DaoControlPresupuesto.LoadGraficoVentas(CODCANAL, RUTCLIENTE, MES);
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadGraficoProvisionFacturas(string CODCANAL, string RUTCLIENTE, string MES)
        {
            var resultado = WebBiotec.Models.DAO.DaoControlPresupuesto.LoadGraficoProvisionFacturas(CODCANAL, RUTCLIENTE, MES);
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadGraficoDetalleCuenta(string CODCANAL, string RUTCLIENTE, string MES)
        {
            var resultado = WebBiotec.Models.DAO.DaoControlPresupuesto.getDetallePorCuentaGrafico(CODCANAL, RUTCLIENTE, MES);
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadFacturasJson(string CODCANAL, string RUTCLIENTE)
        {
            var resultado = WebBiotec.Models.DAO.DaoControlDocumento.getFacturas(CODCANAL, RUTCLIENTE);
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadDetalleFacturasJson(string CODCANAL, string RUTCLIENTE, string FACTURA)
        {
            var resultado = WebBiotec.Models.DAO.DaoControlDocumento.getDetalleFacturas(CODCANAL, RUTCLIENTE, FACTURA);
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadCuentasClientes(string RUTCLIENTE)
        {
            var resultado = WebBiotec.Models.DAO.DaoControlDocumento.getClientesCuentas(RUTCLIENTE);
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LimpiarEstadoFactura(string RUTCLIENTE, string FACTURA, string FECHAEMISION, string FECHAGASTO)
        {
            WebBiotec.Models.DAO.DaoControlDocumento.setFacturasEstados(RUTCLIENTE, FACTURA, FECHAEMISION, FECHAGASTO);
            var resultado = "Factura " + FACTURA + " Actualizada";
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        public JsonResult getDetallesDocumentosCuenta(string CODCANAL, string RUTCLIENTE, string MES, string CUENTA)
        {
            var result = WebBiotec.Models.DAO.DaoControlPresupuesto.getDetallesDocumentosCuenta(CODCANAL, RUTCLIENTE, MES, CUENTA);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult mantEstadoFactura()
        {
            return View();
        }
     
    }
}

btc/Web/WebBiotec/Views/TradeMarketing/respaldo/ControlDocumentos.cshtml
@{
    ViewBag.Title = "ControlDocumentos";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<style>
    #chartdivVentasMM, #chartdivRelacionProvision, #chartdivPresupuestoEjecucion {
        width: 100%;
        height: 300px;
        background-color: rgb(255, 255, 255);
        overflow: visible;
        text-align: left;
    }

    #chartdivRelacionProvision {
        width: 100%;
        height: 400px;
        background-color: rgb(255, 255, 255);
        overflow: visible;
        text-align: left;
    }
</style>


<div class="row x_title">
    <div class="col-md-6">
        <h3>APROBACIÓN DE DOCUMENTOS<small></small></h3>
    </div>

</div>


<div class="panel-group" id="accordion" style="padding-top:10px; padding-bottom:10px;">
    <div class="panel" style="background-color:#003140;">
        <div class="panel-heading" style="color:#ffffff;background-color:#3e4855;margin:0px !important">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="">Filtros</a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body" style="color:#ffffff">

                <form class="form-horizontal bordered-row">

                    <div class="row" style="padding-bottom:10px">
                        <div class="col-lg-12 col-md-12 col-xs-12" >
                    
                                <label class="col-lg-2 col-md-4 col-xs-12 control-label" style="text-align:left;">CLIENTES:</label>
                                <div class="col-lg-8 col-md-8 col-xs-12">
                                    <input id="comboboxClientes" title="Clientes" value="Seleccionar" style="min-width: 40%" />
                                </div>

                        </div>
                    </div>


                    <div class="row" style="padding-bottom:10px">
                        <div class="col-lg-12 col-md-12 col-xs-12">
                            <label class="col-lg-2 col-md-4 col-xs-12 control-label" style="text-align:left;">N° DE DOCUMENTO:</label>
                            <div class="col-lg-8 col-md-8 col-xs-12">
                                <input id="comboboxNumeroDocumento" title="Documentos" value="Seleccionar" style="min-width: 40%" />
                            </div>

                        </div>
                    </div>


                    <div class="row" style="padding-bottom:10px">
                        <div class="col-lg-12 col-md-12 col-xs-12">
                            <label class="col-lg-2 col-md-4 col-xs-12 control-label" style="text-align:left;">TIPO DE FACTURA:</label>
                            <div class="col-lg-8 col-md-8 col-xs-12">
                                <input class="k-textbox col-lg-12 col-md-12 col-xs-12" value="" id="txtTipoFactura" type="text" style="min-width: 40%"readonly />
                            </div>
                        </div>
                    </div>

                    <div class="row" style="padding-bottom:30px">
                        <div class="col-lg-12 col-md-12 col-xs-12">
                            <label class="col-lg-2 col-md-4 col-xs-12 control-label" style="text-align:left;">CUENTA CONTABLE ASIGNADA:</label>
                            <div class="col-lg-8 col-md-8 col-xs-12">
                                <input class="k-textbox col-lg-12 col-md-12 col-xs-12" value="" id="txtCuentaContable" type="text" style="min-width: 40%" readonly />
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-lg-6 col-md-12 col-sm-6 pull-left" style="padding-bottom:30px">
                                                                   
                                    <div class="col-lg-4 col-md-4 col-xs-12">
                                        <input type="radio" name="engineeFacturaEstado" id="engine7" class="k-radio" checked="checked">
                                        <label class="k-radio-label" for="engine7">APROBADO</label>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-xs-12">
                                        <input type="radio" name="engineeFacturaEstado" id="engine8" class="k-radio">
                                        <label class="k-radio-label" for="engine8">RECLASIFICAR</label>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-xs-12">
                                        <input type="radio" name="engineeFacturaEstado" id="engine9" class="k-radio">
                                        <label class="k-radio-label" for="engine9">RECHAZAR</label>
                                    </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 pull-right">
                            @*<div class="form-horizontal bordered-row pull-left">*@
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <button type="button" class="btn btn-default" id="linkLimpiar" onclick="Limpiar();" style="margin-bottom:20px; margin-right:10px">Ver</button>
                                    <button type="button" class="btn btn-default" id="linkAceptar" onclick="Filtrar();" style="margin-bottom:20px">Aceptar</button>
                                    
                                </div>
                            @*</div>*@
                        </div>
                    </div>


            </form>


            </div>
        </div>
    </div>
</div>



<script>

    $(document).ready(function () {

        kendo.culture("es-CL");
        // create DatePicker from input HTML element
        $("#datepicker").kendoDatePicker();

        $("#monthpicker").kendoDatePicker({
            // defines the start view
            start: "year",

            // defines when the calendar should return date
            depth: "year",

            // display month and year in the input
            //format: "MMMM yyyy",
            format: "MM-yyyy",
            maxDate: '0',

            // specifies that DateInput is used for masking the input element
            dateInput: true,
            animation: {
                close: {
                    effects: "zoom:out",
                    duration: 300
                }
            }

        });

        var clientesDS = new kendo.data.DataSource({
            transport: {
                read: {
                    url: '@Url.Action("cargarClientes", "PortalWeb")',
                    dataType: "json",
                    //data: {
                    //    cod: "ZONASLOCALES",
                    //    idcanal: canal,
                    //    idzona: zona,
                    //    idregion: region,
                    //    iddistribuidor: distribuidor
                    //}
                }
            },
            schema: {
                model: {
                    fields: {
                        valor: { type: "string" },
                        texto: { type: "string" }
                    }
                }
            }
        });

        $("#comboboxClientes").kendoComboBox({
            clearButton: false,
            dataValueField: "valor",
            dataTextField: "texto",
            dataSource: clientesDS,
            animation: {
                close: {
                    effects: "zoom:out",
                    duration: 300
                }
            }
        });


        var documentosDS = new kendo.data.DataSource({
            transport: {
                read: {
                    url: '@Url.Action("cargarClientes", "PortalWeb")',
                    dataType: "json",
                }
            },
            schema: {
                model: {
                    fields: {
                        valor: { type: "string" },
                        texto: { type: "string" }
                    }
                }
            }
        });

        $("#comboboxNumeroDocumento").kendoComboBox({
            placeholder: "Todos",
            clearButton: false,
            dataValueField: "valor",
            dataTextField: "texto",
            dataSource: documentosDS,
            animation: {
                close: {
                    effects: "zoom:out",
                    duration: 300
                }
            }
        });

    });

</script>